# Generated by Django 5.2.8 on 2025-12-05 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, choices=[('algorithms', 'Основы алгоритмизации и программирования'), ('web_design', 'Основы веб-дизайна'), ('databases', 'Основы проектирования баз данных')], max_length=200, verbose_name='Наименование курса')),
                ('start_date', models.DateField(verbose_name='Желаемая дата начала')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('phone', 'Перевод по номеру телефона')], max_length=10, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Идет обучение'), ('done', 'Обучение завершено')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
